version: '3'

services:
  app:
    build: ./
    container_name: PythonDocker
    tty: true
    stdin_open: true
    ports:
      - "127.0.0.1:5678:5678"
    volumes:
      - ./project:/code/project
    